application_name: &application BookinS
cache:
  directory: ~/.cache/BookinS
  verbose: True
fcache:
  isbn: True
calibre_db:
  ~/Dropbox/CalibreLibraryi
database:
  ebook
ebook_extensions: ["epub"]

logging:
  format: '%(asctime)-15s %(clientip)s %(user)-8s %(message)s'
  level:
    gui: 20
    bookinfo: debug

goodreads:
  key: 'iKEG2vmZFhfw1GkHkMRk7w'
  url:
    isbn: "https://www.goodreads.com/book/isbn/{}?key={}"
    id: "https://www.goodreads.com/book/show/{}.xml?key={}"

openlibrary:
  cover_url: 'http://covers.openlibrary.org/b/ISBN/{}-L.jpg'
  data_url: "https://openlibrary.org/api/books?bibkeys=ISBN:{}&format=json&jscmd=data"

librarything:
  key: '3a88914e5ef7d402e75bdbdcda333f4f'
  url:
    isbn: 'http://www.librarything.com/services/rest/1.1/?method=librarything.ck.getwork&isbn={}&apikey={}'
    id: 'http://www.librarything.com/services/rest/1.1/?method=librarything.ck.getwork&id={}&apikey={}'

anchor: &anchor default_name
alias: *anchor

language_code:
  fr: fre
  en: eng
  it: ita